---
abstract: 'display the Schwartz ratio of the distribution upon release'
author:
  - 'Yanick Champoux <yanick@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::DZil: '0'
  Test::Deep: '0'
  Test::MockObject: '0'
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-SchwartzRatio
provides:
  Dist::Zilla::Plugin::SchwartzRatio:
    file: lib/Dist/Zilla/Plugin/SchwartzRatio.pm
    version: v0.3.4
requires:
  Dist::Zilla::Role::AfterRelease: '0'
  Dist::Zilla::Role::Plugin: '0'
  List::UtilsBy: '0'
  MetaCPAN::Client: '0'
  Moose: '0'
  perl: v5.14.0
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/Dist-Zilla-Plugin-SchwartzRatio/issues
  homepage: https://github.com/yanick/Dist-Zilla-Plugin-SchwartzRatio
  repository: https://github.com/yanick/Dist-Zilla-Plugin-SchwartzRatio.git
version: 0.3.4
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributor_covenant:
  version: 0.01
x_contributors:
  - 'brian greenfield <0briang0@gmail.com>'
  - 'Yanick Champoux <yanick@babyl.ca>'
x_generated_by_perl: v5.20.2
x_serialization_backend: 'YAML::Tiny version 1.67'
